version: "3.8"

services:

  backend_test:
    container_name: backend_test
    build:
      context: ./backend
      dockerfile: Dockerfile_backend_tests
    volumes:
      - ./backend:/backend
    environment:
      PG_DATABASE: database_test
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_DB: postgres_test
      POSTGRES_PORT: 5432
      ES_DATABASE: es_test
      ES_PORT: 9200
    networks:
      - web_app_network
    ports:
      - '127.0.0.1:8000:8000'
    command: sh -c "alembic upgrade heads && 
                    python db/es/migrations.py"
    depends_on:
      elasticsearch_test:
        condition: service_healthy
      database_test:
        condition: service_healthy

  database_test:
    image: postgres:15-alpine3.18
    container_name: database_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_test -d postgres_test" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_DB: postgres_test
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - web_app_network
    restart: always

  elasticsearch_test:
    container_name: es_test
    image: elasticsearch:8.11.3
    healthcheck:
      test: curl -s http://es_test:9200 > /dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - web_app_network
    ports:
      - "127.0.0.1:9200:9200"
    restart: always

networks:
  web_app_network:
    driver: bridge