"""alter table Rubric

Revision ID: ed8593cc4325
Revises: 
Create Date: 2023-12-27 15:54:33.988188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8593cc4325'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rubrics', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rubrics')
    # ### end Alembic commands ###
