name: Python Application Test

on:
  push:
    branches: [ main, backend/** ]
  pull_request:
    branches: [ main, backend/** ]

jobs:
    test_backend:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Lint with flake8
          run: |
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Docker compose up and Running test
          run: docker compose -f docker-compose-tests.yaml up -d
